language: c

branches:
 - tome

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y git autoconf sqlite3 libsqlite3-dev bison flex libncursesw5 libncursesw5-dev libncurses5-dev

script: ./autogen.sh --enable-sqlite --enable-shmem && make
